name: ReVanced Experimental Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Download APK
        run: ./download.sh
        env: 
          DW_KEY: ${{ secrets.DW_KEY }}

      - name: Build APKs, force patches on untested YouTube versions
        run: ./build_revanced.sh experimental

      - name: Set current date as env variable
        run: echo "date_now=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          draft: true
          title: "Revanced Dev ${{ env.date_now }}"
          files: |
            build/*.apk
            vanced-microG.apk
